parameters:
    bd_site_reader_proxy.routing_loader.yaml_finder.factory_class: BD\SiteReaderProxyBundle\DependencyInjection\Factory\YamlSitesRoutesFinderFactory

services:
    bd_site_reader_proxy.routing_loader:
        class: BD\SiteReaderProxyBundle\Routing\SiteRoutingLoader
        tags:
            - { name: routing.loader }
        arguments:
            - @bd_site_reader_proxy.routing_loader.finder
            - %app_uri%

    # A pre-configured instance of the finder that locates site domain routing files
    bd_site_reader_proxy.routing_loader.finder:
        class: Symfony\Component\Finder\Finder
        factory_class: %bd_site_reader_proxy.routing_loader.yaml_finder.factory_class%
        factory_method: build
        arguments: [@bd_site_reader_proxy.routing_loader.path_getter, %app_uri%]

    # Direct call to the FileLocator's locate method
    bd_site_reader_proxy.routing_loader.path_getter:
        lazy: true
        class: StdClass
        factory_service: file_locator
        factory_method: locate
        arguments: ['@@BDSiteReaderProxyBundle/Resources/config/sites_routing/']


    bd_site_reader_proxy.site.controller.lmd:
        class: BD\SiteReaderProxyBundle\Controller\LmdSiteController
