parameters:
    bd_site_reader_proxy.routing_loader.yaml_finder.factory_class: BD\SiteReaderProxyBundle\DependencyInjection\Factory\YamlSitesRoutesFinderFactory

services:
    bd_site_reader_proxy.routing_loader:
        class: BD\SiteReaderProxyBundle\Routing\SiteRoutingLoader
        tags:
            - { name: routing.loader }
        arguments:
            - @bd_site_reader_proxy.routing_loader.finder
            - @kernel
            - %app_uri%

    # A pre-configured instance of the finder that locates site domain routing files
    bd_site_reader_proxy.routing_loader.finder:
        class: Symfony\Component\Finder\Finder
        factory_class: %bd_site_reader_proxy.routing_loader.yaml_finder.factory_class%
        factory_method: build

    bd_site_reader_proxy.browser:
        class: BD\SiteReaderProxyBundle\Proxy\BaseWebsiteBrowser
        abstract: true
        calls:
            - [setGuzzleClient, [@bd_site_reader_proxy.guzzle_client]]

    bd_site_reader_proxy.guzzle_client:
        class: GuzzleHttp\Client
