bd_mediapart_site_reader.articles_feed:
    path: /articles/feed
    defaults: { _controller: bd_mediapart_site_reader.controller.mediapart:proxyArticlesFeedAction }

bd_mediapart_site_reader.article:
    path: /journal/{uri}
    defaults: { _controller: bd_mediapart_site_reader.controller.mediapart:proxyArticleAction }
    requirements:
        uri: .+
