parameters:
#    bd_site_reader_proxy_mediapart_site.example.class: BD\SiteReaderProxy\MediapartSiteBundle\Example

services:
#    bd_site_reader_proxy_mediapart_site.example:
#        class: %bd_site_reader_proxy_mediapart_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
